name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: DEBUG - Show requirements.txt content
        run: cat requirements.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/book-recommender:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 30m
          script: |
            cd ~/semantic-book-recommender
            
            git pull origin main
            
            docker build -t book-recommender .
            
            docker stop book-recommender-app || true
            docker rm book-recommender-app || true
            
            GOOGLE_CREDS_B64=$(echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' | base64 -w 0)

            docker run -d -p 8501:8501 \
              -e QDRANT_API_KEY='${{ secrets.QDRANT_API_KEY }}' \
              -e QDRANT_URL='${{ secrets.QDRANT_URL }}' \
              -e GOOGLE_CREDENTIALS_B64="$GOOGLE_CREDS_B64" \
              --name book-recommender-app \
              book-recommender