name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: DEBUG - Show requirements.txt content
        run: cat requirements.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/book-recommender:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 30m
          script: |
            mkdir -p /home/ubuntu/semantic-book-recommender/.streamlit
            
            docker stop $(docker ps -a -q) || true
            docker rm $(docker ps -a -q) || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/book-recommender:latest
            
            docker run -d -p 8501:8501 \
              -v /home/ubuntu/semantic-book-recommender/.streamlit/secrets.toml:/app/.streamlit/secrets.toml \
              ${{ secrets.DOCKERHUB_USERNAME }}/book-recommender:latest